### ISSUE TITLE
Bug: Pairing won't work for devices in different networks

### ISSUE THREAD

**Issue by Manrochri** [schlagmichdoch/PairDrop#130]
**Describe the bug**
When trying to pair an android using mobile data to a computer, the paired devices won't appear and in the list of paired devices all are marked as "undefined". So, it won't let me send text or files between my phone and a computer that are not in the same network. 

**To Reproduce**
1. Go to the pair icon
2. Pair the devices using either the qr code or the pin code
3. Click on pair
4. See the list of paired devices on the button "edit paired devices"

**Expected behavior**
All paired devices appear as "undefined" and those won't be paired

**Screenshots**
![image](https://github.com/schlagmichdoch/PairDrop/assets/119143925/b6c1220e-193c-414e-9394-620656ed8b43)
![Screenshot_20230726-200108](https://github.com/schlagmichdoch/PairDrop/assets/119143925/8dcbd429-30b4-469d-8d2c-f19219148f30)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 19045.3208
 - Browser Google Chrome
 - Version 115.0.5790.110

**Smartphone (please complete the following information):**
 - Device: Huwei Y7 2019
 - OS: Android 8 
 - Browser Pogresive web app Pairdrop from the Google play

**Self-Hosted**
No

**Additional context**
I used to pair my phone to a computer (both of them in different networks) and it used to work flawlessly. I didn't use to have problems with that kind of pairing. I use pairing on Pairdrop because I found that to be a practical way to share links from my phone to a computer from a classroom without having to log in into any kind of app or website.

**Comment by schlagmichdoch** [comment]
This should be fixed now. Please try again!

**Comment by Manrochri** [comment]
I tried again, but unfortunately I still have the same issue.
________________________________
De: schlagmichdoch ***@***.***>
Enviado: jueves, 27 de julio de 2023 4:47
Para: schlagmichdoch/PairDrop ***@***.***>
Cc: CHRISTIAN MANUEL RODRIGUEZ CHILET ***@***.***>; Author ***@***.***>
Asunto: Re: [schlagmichdoch/PairDrop] Bug:/Enhancement:/Feature Request: Pairing won't work for devices in different networks (Issue #130)


This should be fixed now. Please try again!

**Comment by marcoportincasa** [comment]
> This should be fixed now. Please try again!

any update on this bug? if no -> @schlagmichdoch tag me when it's fixed....please

**Comment by Manrochri** [comment]
Unfortuntately, I'm still having the same issue when I tried to pair my device that uses mobile data to a computer in a different network.



________________________________
De: marcoportincasa ***@***.***>
Enviado: viernes, 28 de julio de 2023 5:22
Para: schlagmichdoch/PairDrop ***@***.***>
Cc: CHRISTIAN MANUEL RODRIGUEZ CHILET ***@***.***>; Author ***@***.***>
Asunto: Re: [schlagmichdoch/PairDrop] Bug:/Enhancement:/Feature Request: Pairing won't work for devices in different networks (Issue #130)


This should be fixed now. Please try again!

any update on this bug? if no -> @schlagmichdoch<https://github.com/schlagmichdoch> tag me when it's fixed....please

**Comment by schlagmichdoch** [comment]
@Manrochri @marcoportincasa Please try again! I cannot reproduce the bug anymore.

**Comment by Manrochri** [comment]
The issue was finally solved. At first it didn't worked but after installing the app again on my phone and changing the name of both devices it works as it used to do before I reported the issue. Thank you so much.
________________________________
De: schlagmichdoch ***@***.***>
Enviado: sábado, 29 de julio de 2023 14:10
Para: schlagmichdoch/PairDrop ***@***.***>
Cc: CHRISTIAN MANUEL RODRIGUEZ CHILET ***@***.***>; Mention ***@***.***>
Asunto: Re: [schlagmichdoch/PairDrop] Bug:/Enhancement:/Feature Request: Pairing won't work for devices in different networks (Issue #130)


@Manrochri<https://github.com/Manrochri> @marcoportincasa<https://github.com/marcoportincasa> Please try again! I cannot reproduce the bug anymore.

**Comment by schlagmichdoch** [comment]
Great! Thanks for reporting back! I’ll close this then.

**Comment by s-rog** [comment]
I'm having the same issue when trying to pair devices across VLANs. Running 1.7.6 through a reverse proxy with the container running in one of the VLANs.

I tried running both clients in each LAN and everything works, perhaps a firewall allow rule is needed? Or does the pairdrop server need to be run from a different LAN from the clients to route correctly?

(also the pairdrop.net server works on both clients)

**Comment by schlagmichdoch** [comment]
@s-rog Do you have included a TURN server in your setup?

**Comment by s-rog** [comment]
Negative, is that required for pairdrop to work for my setup?

**Comment by louis-pre** [comment]
Same, I can reproduce it both self-hosted and paidrop.net 
I could only try with my phone (phone on network) and computer (behind NAT) for now

**Comment by s-rog** [comment]
my vlans are setup on pfsense

**Comment by louis-pre** [comment]
> @louis-pre By chance, Is your NAT network run by a pfSense box?

It is not, I tested directly connected to XFinity's router/modem

I can do some more tests this evening if you wish

**Comment by schlagmichdoch** [comment]
We need to differentiate between self-hosting and the instance running on pairdrop.net when discussing this issue

---

> Negative, is that required for pairdrop to work for my setup?

Yes, a TURN Server is required to route your traffic if you use devices behind different NATs.

See [Technical Documentation](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/technical-documentation.md) and [Deployment Notes](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md).

---

The instance on pairdrop.net is using the TURN server correctly again. Please try again and give feedback whether we can close this issue @louis-pre

**Comment by s-rog** [comment]
Are different subnets considered different NATs? or is a STUN server needed whenever a firewall involved?
(also I just gave pairdrop.net another go and two clients on different subnets/VLANs detect each other without pairing)

**Comment by louis-pre** [comment]
@schlagmichdoch Thanks a lot, pairdrop.net works again for me too in all the uses-cases I have tested prior

I have not re-tested the self-hosted version again but I'm sure I can make it work if it works in the hosted version 👍

**Comment by schlagmichdoch** [comment]
> (also I just gave pairdrop.net another go and two clients on different subnets/VLANs detect each other without pairing

Probably both clients have the same public IP address and are therefor shown to each other by PairDrop. The connection still only works when including a TURN server in the setup. Beware that snapdrop.net will show both devices to each other as well but actually sending sth will fail due to the lack of a TURN server.

 

> Are different subnets considered different NATs? or is a TURN server needed whenever a firewall involved? (also I just gave pairdrop.net another go and two clients on different subnets/VLANs detect each other without pairing)
> 
> Edit: I read up more on TURN servers and it is indeed necessary, was hoping I could just poke a hole in my own subnet firewall!

Sadly this is not the case. If all devices can use IPv6 it might be possible to host PairDrop on IPv6 only which would eliminate the need of a TURN server but also the auto discovery feature for clients in the same network as every devices has its own IPv6 address.
If you are going to do some more testing I would appreciate if you would share your results! Maybe we can include them somewhere in the docs.

I'll close this for now. Thanks @everyone for testing!
